# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f454f0840c0aeefb7b9ca70e3fb9defb4713f20f047bb0a92990822175a8cdac2763a59af383865873dd6f22d76683ab29d03973add549aa6ca5e57649aa56c7

test:
  secret_key_base: 513301481a0e2f193fde8f75c80dae625004b57ac899955d65d3a9d718874e8fa08927acd051d0650eb52a8b34a987b696bcd79e667691cded87fe549dd88b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
